version: '3.8'

services:
  latex-api:
    build: .
    image: ghcr.io/arman-shirzad/latextopdf:latest
    container_name: latex-backend
    restart: always
    environment:
      - ALLOWED_ORIGINS=*
    networks:
      - arman_net

networks:
  arman_net:
    external: true
    name: arman_net
